FROM ubuntu:20.04

RUN apt update

#### common ####
RUN apt install -y git make

#### risc-v toolchain ####
RUN apt install -y autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex gperf libtool patchutils bc zlib1g-dev libexpat-dev
RUN DEBIAN_FRONTEND=noninteractive apt install -y texinfo

#### qemu ####
RUN apt install -y ninja-build pkg-config libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev

#### x86 ####
RUN apt install -y gcc

#### risc-v ####
RUN cd && git clone https://github.com/riscv/riscv-gnu-toolchain.git \
	&& cd riscv-gnu-toolchain \
	&& git checkout -b 20210807 2021.08.07 \
	&& ./configure --prefix=/opt/gcc/riscv/newlib/64/ && make -j6 \
	&& ./configure --prefix=/opt/gcc/riscv/linux/64/ && make linux -j6 \
	&& make clean \
	&& ./configure --prefix=/opt/gcc/riscv/newlib/32/ --with-arch=rv32gc --with-abi=ilp32d && make -j6 \
	&& ./configure --prefix=/opt/gcc/riscv/linux/32/ --with-arch=rv32gc --with-abi=ilp32d && make linux -j6 \
	&& make clean \
	&& ./configure --prefix=/opt/gcc/riscv/multilib/newlib/ --enable-multilib && make -j6 \
	&& ./configure --prefix=/opt/gcc/riscv/multilib/linux/ --enable-multilib && make linux -j6 \
	&& make clean \
	&& echo "export PATH=\$PATH:/opt/gcc/riscv/newlib/64/bin:/opt/gcc/riscv/newlib/32/bin:/opt/gcc/riscv/linux/64/bin:/opt/gcc/riscv/linux/32/bin" >> ~/.bashrc \
	&& echo "#export PATH=\$PATH:/opt/gcc/riscv/multilib/newlib/bin:/opt/gcc/riscv/multilib/linux/bin" >> ~/.bashrc \
	&& cd && rm -fr ~/riscv-gnu-toolchain

RUN cd && git clone https://github.com/qemu/qemu.git \
	&& cd qemu \
	&& git checkout -b v520 v5.2.0 \
	&& mkdir build && cd build \
	&& ../configure --prefix=/opt/qemu/ --target-list=riscv64-softmmu,riscv32-softmmu,riscv64-linux-user,riscv32-linux-user && make -j6 && make install \
	&& echo "export PATH=\$PATH:/opt/qemu/bin" >> ~/.bashrc \
	&& cd && rm -fr ~/qemu
