FROM ubuntu:12.04

RUN apt-get update

#### x86_64 ####
RUN apt-get install -y gcc bin86 wget binutils libc-dev-bin libc6-dev linux-libc-dev manpages manpages-dev

# 安装gcc 3.4版本, 并且修改系统默认gcc为gcc 3.4
RUN mkdir /opt/amd64 \
	&& cd /opt/amd64 \
	&& wget http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-3.4/cpp-3.4_3.4.6-6ubuntu5_amd64.deb \
	&& wget http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-3.4/g++-3.4_3.4.6-6ubuntu5_amd64.deb \
	&& wget http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-3.4/gcc-3.4_3.4.6-6ubuntu5_amd64.deb \
	&& wget http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-3.4/gcc-3.4-base_3.4.6-6ubuntu5_amd64.deb \
	&& wget http://old-releases.ubuntu.com/ubuntu/pool/universe/g/gcc-3.4/libstdc++6-dev_3.4.6-6ubuntu5_amd64.deb \
	&& dpkg -i *.deb \
	&& cd / \
	&& rm -fr /opt/amd64 \
	&& update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 40 \
	&& update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-3.4 30 \
	&& echo 1 | update-alternatives --config gcc \
	&& echo "export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:\$LIBRARY_PATH" >> ~/.bashrc \
	&& ln -sf /lib/x86_64-linux-gnu/libgcc_s.so.1 /usr/lib/gcc/x86_64-linux-gnu/3.4.6/libgcc_s.so
