FROM ubuntu:10.04

COPY patch/apt/sources.list /etc/apt/
RUN apt-get update

#### x86_64 ####
RUN apt-get install -y gcc make libncurses5-dev wget xz-utils patch pkg-config zlib1g-dev libglib2.0-dev autoconf libtool

# 需要在使用此dockerfile构建docker images前，在PC机执行如下命令：
# $ mkdir package; cd package
# $ wget https://download.qemu.org/qemu-2.0.0.tar.bz2
COPY package/qemu-2.0.0.tar.bz2 /opt
RUN cd /opt \
	&& tar -jxvf qemu-2.0.0.tar.bz2 \
	&& cd qemu-2.0.0 \
	&& ./configure --target-list=x86_64-softmmu \
	&& make \
	&& make install \
	&& cd /opt/ \
	&& rm -fr qemu-*

# 使用apt安装的gdb，执行时会出现Remote 'g' packet reply is too long错误，所以修改gdb源码，然后安装gdb
COPY patch/gdb/gdb_7_8.patch /
RUN wget http://ftp.gnu.org/gnu/gdb/gdb-7.8.tar.xz \
	&& tar -xf gdb-7.8.tar.xz \
	&& cd gdb-7.8/ \
	&& mv /gdb_7_8.patch . \
	&& patch -p1 < gdb_7_8.patch \
	&& ./configure \
	&& make \
	&& make install \
	&& cd / \
	&& rm -fr gdb-7.8*
